'use strict';
export{};

console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);
console.log(Math.floor(Math.random()*8)+1);